// Export all views
export { default as Header } from '@views/components/header'
export { default as PhotographerCard } from '@views/components/photographer-card'
export { default as PhotographerSummary } from '@views/components/photographer-summary'
export { default as FilterMedias } from '@views/components/filter-medias'
export { default as PhotographerMedias } from '@views/components/photographer-medias'
export { default as PhotographerAside } from '@views/components/photographer-aside'
export { default as ModalForm } from '@views/components/modal-form'
export { default as MainHome } from '@views/pages/main-home'
export { default as MainPhotographer } from '@views/pages/main-photographer'
export { default as Main404 } from '@views/pages/main-404'
